[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "pyo3-mixed-py-subdir"
version = "2.1.3"
description = "Implements a dummy function combining rust and python"
readme = "README.md"
edition = "2018"

[dependencies]
pyo3 = { version = "0.17.2", features = ["extension-module"] }

[lib]
name = "pyo3_mixed_py_subdir"
crate-type = ["cdylib"]

[package.metadata.maturin]
python-source = "python"
name = "pyo3_mixed_py_subdir._pyo3_mixed"

[patch.crates-io]
pyo3-ffi = { git = "https://github.com/PyO3/pyo3.git", branch = "main" }
pyo3 = { git = "https://github.com/PyO3/pyo3.git", branch = "main" }
